"""`GET /e/<id>`: the short link the share cards print, and the only server-rendered head we have.

TWO JOBS, AND THE SECOND IS THE ONE THAT NEEDED A ROUTE. A redirect would have covered the first:
a URL printed on an image is a URL somebody retypes, and `/e/2026-09-16-am` is four fewer pieces
of punctuation than `episode.html?id=2026-09-16-am`.

The second cannot be done with a redirect. `web/` has no build step, so `episode.html` is one
static file serving every episode and its <head> can name none of them. Slack, LinkedIn, X and
iMessage read that head and do not run the JavaScript that fills the page in, so before this an
episode shared anywhere unfurled blank -- including the 1200x630 card generated for exactly that
slot. These tests pin the head, the 404s, and the fact that the page still works.
"""

from __future__ import annotations

import json

import pytest
from fastapi.testclient import TestClient

from hn_radio import cards, config


@pytest.fixture
def client(tmp_path, monkeypatch):
    """An app whose episodes directory is one hand-built, priced, pictured episode."""
    monkeypatch.setattr(config, "EPISODES_DIR", tmp_path)
    monkeypatch.setenv("HN_RADIO_BASE_URL", "https://hn.example/episodes")
    d = tmp_path / "2026-09-16-am"
    d.mkdir()
    (d / "episode.json").write_text(json.dumps({
        "id": "2026-09-16-am",
        "title": 'Morning Edition: "quotes" & ampersands',
        "summary": "Three stories.",
        # The app's startup hook rebuilds the feed from this directory, and the feed wants a
        # timestamp on every episode it finds.
        "generated_at": "2026-09-16T10:04:19Z",
        "duration_seconds": 374.91,
        "source_items": [{"hn_id": 1, "title": "A story", "url": "https://example.com"}],
        "segments": [{"role": "anchor", "desk": "anchor", "speaker_key": "Alexis",
                      "voice_id": "flux-alexis-en"}],
        "cost": {"characters": 5426, "usd": 0.24417, "episodes_per_credit": 819,
                 "credit_usd": 200.0, "rate_usd_per_1k": 0.045, "plan": "payg"},
    }))
    from backend.app import app
    # Entering the context runs the startup hook, which is `publish.rebuild_site` -- so this
    # episode arrives priced and pictured, exactly as it would on a Fly boot. That is the state
    # these tests want to describe, rather than one assembled by hand beside it.
    with TestClient(app) as c:
        yield c, d


def test_it_serves_the_episode_page_with_that_episodes_title(client):
    c, _ = client
    r = c.get("/e/2026-09-16-am")
    assert r.status_code == 200
    # Escaped, because the title is author-controlled text going into HTML.
    assert "<title>Morning Edition: &quot;quotes&quot; &amp; ampersands</title>" in r.text
    assert 'property="og:title"' in r.text
    assert 'content="https://hn.example/e/2026-09-16-am"' in r.text


def test_it_publishes_the_social_card_as_the_open_graph_image(client):
    """The card and the tag are generated by the same commit, and the tag names the size so an
    unfurler does not have to fetch the image to lay out a preview."""
    c, d = client
    assert (d / cards.CARD_JSON).is_file()      # the boot built it; nothing here did
    r = c.get("/e/2026-09-16-am")
    assert 'content="https://hn.example/episodes/2026-09-16-am/card-social.png"' in r.text
    assert 'property="og:image:width" content="1200"' in r.text
    assert 'property="og:image:height" content="630"' in r.text
    assert 'name="twitter:card" content="summary_large_image"' in r.text
    # The alt text rides along, so a screen reader in a client that renders the unfurl gets the
    # cost and the pitch rather than "image".
    assert "$0.24 to render end to end" in r.text


def test_an_episode_with_no_card_gets_no_image_tags_rather_than_a_broken_one(client):
    """A machine with no fonts builds no cards, and that is a normal state. An og:image pointing
    at a 404 unfurls worse than no og:image at all."""
    c, d = client
    (d / cards.CARD_JSON).unlink()
    r = c.get("/e/2026-09-16-am")
    assert r.status_code == 200
    assert "og:image" not in r.text
    assert "twitter:card" not in r.text


def test_the_page_can_still_find_its_own_assets(client):
    """episode.html references brand.css and four scripts relatively, and this route serves it one
    path segment deep. One <base> is the fix; rewriting five attributes would be five chances to
    miss one."""
    c, _ = client
    r = c.get("/e/2026-09-16-am")
    assert '<base href="/">' in r.text
    assert '<script type="module" src="app.js">' in r.text


@pytest.mark.parametrize("bad", [
    "nope",                       # no such episode
    "..%2F..%2Fetc%2Fpasswd",     # the id is joined to a path, so it is pattern-checked first
    "../../etc/passwd",
    "",
])
def test_a_bad_id_is_a_404_and_never_a_file_read(client, bad):
    c, _ = client
    assert c.get(f"/e/{bad}").status_code == 404
